server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/simonqiang/spring-cloud-config-server-repository.git
          default-label: main
          username: simonqiang
          password:
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}c11f5a9622fa4793144a574045e86486ee7369a389fb0ac029b3f9f8b748d2c1ad52f77c81040cfafc3a2a2bf6c3801e'
encrypt:
  key: 'Demo_Pwd!2022'
